spring.application.name=${DISCOVERY_APP_NAME:discovery-server}
server.port=${DISCOVERY_SERVER_PORT:8100}
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.instance.preferIpAddress=false
eureka.client.service-url.defaultZone=${DISCOVERY_URL_DEFAULT:http://discovery-server-container:8100/eureka/}
